"""create core domain tables

Revision ID: 3238df7fb2d5
Revises:
Create Date: 2026-09-06 10:56:33.352152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3238df7fb2d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('public_key_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > created_at', name=op.f('ck_api_keys_expires_at_after_created_at')),
    sa.CheckConstraint('length(trim(key_prefix)) > 0', name=op.f('ck_api_keys_key_prefix_not_blank')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_api_keys_name_not_blank')),
    sa.CheckConstraint('length(trim(public_key_id)) > 0', name=op.f('ck_api_keys_public_key_id_not_blank')),
    sa.CheckConstraint('length(trim(secret_hash)) > 0', name=op.f('ck_api_keys_secret_hash_not_blank')),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name=op.f('ck_api_keys_revoked_at_not_before_created_at')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_api_keys_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('public_key_id', name=op.f('uq_api_keys_public_key_id'))
    )
    op.create_index('ix_api_keys_team_id', 'api_keys', ['team_id'], unique=False)
    op.create_table('team_budgets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_amount >= 0', name=op.f('ck_team_budgets_allocated_amount_non_negative')),
    sa.CheckConstraint('period_end > period_start', name=op.f('ck_team_budgets_period_end_after_start')),
    sa.CheckConstraint('remaining_amount <= allocated_amount', name=op.f('ck_team_budgets_remaining_within_allocated')),
    sa.CheckConstraint('remaining_amount >= 0', name=op.f('ck_team_budgets_remaining_amount_non_negative')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_budgets_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_budgets')),
    sa.UniqueConstraint('team_id', 'period_start', name='uq_team_budgets_team_period_start')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('budget_period_start', sa.Date(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='status_values', native_enum=False, create_constraint=True), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reserved_cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("request_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_idempotency_keys_request_hash_lowercase_hex')),
    sa.CheckConstraint("status <> 'completed' OR response_snapshot IS NOT NULL", name=op.f('ck_idempotency_keys_completed_has_response_snapshot')),
    sa.CheckConstraint("status <> 'failed' OR error_code IS NOT NULL", name=op.f('ck_idempotency_keys_failed_has_error_code')),
    sa.CheckConstraint("status <> 'pending' OR completed_at IS NULL", name=op.f('ck_idempotency_keys_pending_has_no_completed_at')),
    sa.CheckConstraint("status = 'completed' OR response_snapshot IS NULL", name=op.f('ck_idempotency_keys_non_completed_has_no_response_snapshot')),
    sa.CheckConstraint("status = 'failed' OR error_code IS NULL", name=op.f('ck_idempotency_keys_non_failed_has_no_error_code')),
    sa.CheckConstraint("status = 'pending' OR completed_at IS NOT NULL", name=op.f('ck_idempotency_keys_settled_has_completed_at')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_idempotency_keys_expires_at_after_created_at')),
    sa.CheckConstraint('length(request_hash) = 64', name=op.f('ck_idempotency_keys_request_hash_length_64')),
    sa.CheckConstraint('length(trim(idempotency_key)) > 0', name=op.f('ck_idempotency_keys_idempotency_key_not_blank')),
    sa.CheckConstraint('reserved_cost >= 0', name=op.f('ck_idempotency_keys_reserved_cost_non_negative')),
    sa.ForeignKeyConstraint(['team_id', 'budget_period_start'], ['team_budgets.team_id', 'team_budgets.period_start'], name='fk_idempotency_keys_team_budget', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('team_id', 'idempotency_key', name='uq_idempotency_keys_team_key')
    )
    op.create_index('ix_idempotency_keys_status_expires_at', 'idempotency_keys', ['status', 'expires_at'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key_id', sa.Uuid(), nullable=False),
    sa.Column('primary_provider', sa.String(length=64), nullable=False),
    sa.Column('primary_model', sa.String(length=128), nullable=False),
    sa.Column('final_provider', sa.String(length=64), nullable=True),
    sa.Column('final_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', name='status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'failed' OR error_code IS NOT NULL", name=op.f('ck_usage_records_failed_has_error_code')),
    sa.CheckConstraint("status <> 'succeeded' OR (final_provider IS NOT NULL AND final_model IS NOT NULL)", name=op.f('ck_usage_records_succeeded_has_final_provider_and_model')),
    sa.CheckConstraint("status <> 'succeeded' OR error_code IS NULL", name=op.f('ck_usage_records_succeeded_has_no_error_code')),
    sa.CheckConstraint('actual_cost >= 0', name=op.f('ck_usage_records_actual_cost_non_negative')),
    sa.CheckConstraint('completion_tokens >= 0', name=op.f('ck_usage_records_completion_tokens_non_negative')),
    sa.CheckConstraint('error_code IS NULL OR length(trim(error_code)) > 0', name=op.f('ck_usage_records_error_code_not_blank')),
    sa.CheckConstraint('final_model IS NULL OR length(trim(final_model)) > 0', name=op.f('ck_usage_records_final_model_not_blank')),
    sa.CheckConstraint('final_provider IS NULL OR length(trim(final_provider)) > 0', name=op.f('ck_usage_records_final_provider_not_blank')),
    sa.CheckConstraint('latency_ms >= 0', name=op.f('ck_usage_records_latency_ms_non_negative')),
    sa.CheckConstraint('length(trim(primary_model)) > 0', name=op.f('ck_usage_records_primary_model_not_blank')),
    sa.CheckConstraint('length(trim(primary_provider)) > 0', name=op.f('ck_usage_records_primary_provider_not_blank')),
    sa.CheckConstraint('prompt_tokens >= 0', name=op.f('ck_usage_records_prompt_tokens_non_negative')),
    sa.ForeignKeyConstraint(['idempotency_key_id'], ['idempotency_keys.id'], name=op.f('fk_usage_records_idempotency_key_id_idempotency_keys'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records')),
    sa.UniqueConstraint('idempotency_key_id', name=op.f('uq_usage_records_idempotency_key_id'))
    )
    op.create_index('ix_usage_records_created_at', 'usage_records', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_records_created_at', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('ix_idempotency_keys_status_expires_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('team_budgets')
    op.drop_index('ix_api_keys_team_id', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('teams')
    # ### end Alembic commands ###
